In [2]:
import torch
print(torch.__version__)

1.4.0+cpu


In [3]:
def activation(x):
    return 1/(1 + torch.exp(-x))


In [4]:
# Generating some data
torch.manual_seed(7)

features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [12]:
%time
y = activation(torch.sum(features * weights) + bias)
print(y)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.72 µs
tensor([[0.1595]])


In [13]:
%time
# We can also used the inbuilt function for a more optimized approach: torch.mm()
y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.25 µs
tensor([[0.1595]])


In [15]:
# Let us implement the neural network shown in the lectures.
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [16]:
# Calculation of the output, given the input neural network
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [21]:
# Interconversion between numpy and torch
import numpy as np

a = np.random.rand(4,3)
a

array([[0.75040913, 0.94340427, 0.30270355],
       [0.19549582, 0.09264196, 0.32269682],
       [0.68814833, 0.7966771 , 0.40658922],
       [0.1542091 , 0.47791919, 0.84098367]])

In [19]:
b = torch.from_numpy(a)
b

tensor([[0.8360, 0.3152, 0.9581],
        [0.0057, 0.1699, 0.2950],
        [0.3736, 0.2447, 0.7523],
        [0.9353, 0.5092, 0.7394]], dtype=torch.float64)

In [22]:
b.numpy()

array([[0.83600194, 0.31523686, 0.95812308],
       [0.00565275, 0.1699347 , 0.29502984],
       [0.37363133, 0.24472427, 0.75229469],
       [0.93526662, 0.50916685, 0.73942393]])

In [23]:
# Note that torch and numpy array share the memory, so if, say, the torch array has some changes,
# the corresponding numpy array, which shares the same object, shall observe the similar change
b.mul_(2)

tensor([[1.6720, 0.6305, 1.9162],
        [0.0113, 0.3399, 0.5901],
        [0.7473, 0.4894, 1.5046],
        [1.8705, 1.0183, 1.4788]], dtype=torch.float64)

In [24]:
a

array([[0.75040913, 0.94340427, 0.30270355],
       [0.19549582, 0.09264196, 0.32269682],
       [0.68814833, 0.7966771 , 0.40658922],
       [0.1542091 , 0.47791919, 0.84098367]])